[package]
name = "rust-ci-test"
version = "0.1.0"
authors = ["Sam van der Kris <samvdkris@disroot.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]